"""Add roles enum

Revision ID: 100eb9aacc0d
Revises: 3fc93407449d
Create Date: 2023-10-11 22:27:43.508323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100eb9aacc0d'
down_revision: Union[str, None] = '3fc93407449d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='user_role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='user_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
