"""initial_migration

Revision ID: 22ddadd022a9
Revises: e7eece9bb2bd
Create Date: 2023-10-16 11:50:40.084944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ddadd022a9'
down_revision: Union[str, None] = 'e7eece9bb2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
