"""Removed refresh tokens

Revision ID: 3fc93407449d
Revises: ea83475987d1
Create Date: 2023-10-11 19:24:14.956384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc93407449d'
down_revision: Union[str, None] = 'ea83475987d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
