"""initial_migration

Revision ID: e7eece9bb2bd
Revises: 6f5010e8a22a
Create Date: 2023-10-16 11:47:44.504354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eece9bb2bd'
down_revision: Union[str, None] = '6f5010e8a22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'image')
    # ### end Alembic commands ###
